import { NextRequest, NextResponse } from "next/server"
import database from "@/lib/database/db"
import { RowDataPacket } from "mysql2"
import { Books } from "@/types/Books"
import { BookCopy } from "@/types/BookCopy"

interface RawBookRow extends RowDataPacket {
  id: number;
  title: string;
  author: string;
  description: string;
  year_published: number;
  genres: string | string[] | null;
  copies: string | BookCopy[] | null;
}

export async function GET(req: NextRequest) {
  try {
    const searchParams = req.nextUrl.searchParams
    const query = searchParams.get("query")

    if (!query) {
      return NextResponse.json(
        { message: "A search query 'query' is required" }, 
        { status: 400 }
      )
    }

    const searchTerm = `%${query}%`

    // We use subqueries in the SELECT clause to fetch JSON arrays, 
    // and an EXISTS subquery in the WHERE clause for genre searching.
    const sqlQuery = `
      SELECT 
          b.id, 
          b.title, 
          b.description, 
          b.published_year AS year_published,
          a.name AS author,
          
          (
              SELECT JSON_ARRAYAGG(g.name)
              FROM book_genres bg
              JOIN genres g ON bg.genre_id = g.id
              WHERE bg.book_id = b.id
          ) AS genres,
          
          (
              SELECT JSON_ARRAYAGG(
                  JSON_OBJECT(
                      'id', bc.id,
                      'format', bc.format,
                      'stock', bc.stock,
                      'file_path', bc.file_path,
                      'price', bc.price
                  )
              )
              FROM book_copies bc
              WHERE bc.book_id = b.id
          ) AS copies
          
       FROM books b
       LEFT JOIN authors a ON b.author_id = a.id
       WHERE 
          b.title LIKE ? OR 
          a.name LIKE ? OR 
          EXISTS (
              SELECT 1 
              FROM book_genres search_bg
              JOIN genres search_g ON search_bg.genre_id = search_g.id
              WHERE search_bg.book_id = b.id AND search_g.name LIKE ?
          )
       ORDER BY b.published_year DESC
    `

    // Applied the RawBookRow interface here
    const [rows] = await database.query<RawBookRow[]>(sqlQuery, [
      searchTerm, 
      searchTerm, 
      searchTerm
    ])
    
    // Parse and map the raw rows to match your Books interface
    const formattedRows: Books[] = rows.map((row) => {
      let parsedGenres: string[] = []
      if (typeof row.genres === 'string') {
        parsedGenres = JSON.parse(row.genres) || []
      } else if (Array.isArray(row.genres)) {
        parsedGenres = row.genres
      }

      let parsedCopies: BookCopy[] = []
      if (typeof row.copies === 'string') {
        parsedCopies = JSON.parse(row.copies) || []
      } else if (Array.isArray(row.copies)) {
        parsedCopies = row.copies
      }

      // Filter out any potential nulls generated by the DB JSON aggregation
      parsedGenres = parsedGenres.filter(Boolean)
      parsedCopies = parsedCopies.filter((copy) => copy && copy.id !== null)

      return {
        id: row.id,
        title: row.title,
        author: row.author || "Unknown",
        description: row.description,
        year_published: row.year_published,
        genres: parsedGenres,
        copies: parsedCopies,
      }
    })
    
    return NextResponse.json(formattedRows, { status: 200 })
    
  } catch (error) {
    console.error("Error executing search:", error)
    return NextResponse.json({ message: "Server error" }, { status: 500 })
  }
}